# Generated by Django 4.2 on 2026-03-22 14:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={},
        ),
        migrations.AlterModelOptions(
            name='focussession',
            options={},
        ),
        migrations.AlterModelOptions(
            name='focustask',
            options={'ordering': ['-date', 'priority']},
        ),
        migrations.RenameField(
            model_name='dailycheckin',
            old_name='points_earned',
            new_name='tasks_completed',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='notification_enabled',
            new_name='notifications_enabled',
        ),
        migrations.RemoveField(
            model_name='dailycheckin',
            name='first_check_minutes',
        ),
        migrations.RemoveField(
            model_name='focustask',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar_initial',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.AddField(
            model_name='badge',
            name='xp_reward',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='mood_context',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='tasks_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='xp_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='focustask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('skipped', 'Skipped')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reminder_hour',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='badge',
            name='badge_type',
            field=models.CharField(choices=[('streak', 'Streak'), ('detox', 'Digital Detox'), ('mood', 'Mood'), ('productivity', 'Productivity'), ('journal', 'Journal'), ('boss', 'Boss Level')], max_length=30),
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='badge',
            name='rarity',
            field=models.CharField(default='common', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailycheckin',
            name='mood_label',
            field=models.CharField(choices=[('happy', 'Happy'), ('neutral', 'Neutral'), ('sad', 'Sad'), ('anxious', 'Anxious'), ('angry', 'Angry'), ('bored', 'Bored'), ('energetic', 'Energetic'), ('tired', 'Tired')], default='neutral', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailycheckin',
            name='productivity_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='focussession',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='badge',
            unique_together={('user', 'name')},
        ),
    ]
