# Generated by Django 6.0.3 on 2026-03-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_badge_options_alter_focussession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
