# Generated by Django 6.0.3 on 2026-03-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chatmessage_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycheckin',
            name='minimalism_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='minimalism_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='mood_recovery_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='self_awareness_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='small_win_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='small_win_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
